---

- name: "Ping Tower Endpoint"
  uri:
    url: "{{ ansible_tower.url | default(default_ansible_tower_url) }}/api/v2/ping/"
    user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
    password: "{{ ansible_tower.admin_password }}"
    force_basic_auth: yes
    method: GET
    body_format: 'json'
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    validate_certs: no
  register: tower_ping
