
- block: # when ansible_tower.credentials is defined
  - name: "Get existing credentials"
    uri:
      url: "{{ ansible_tower.url | default(default_ansible_tower_url) }}/api/v2/credentials/"
      user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
      password: "{{ ansible_tower.admin_password }}"
      force_basic_auth: yes
      method: GET
      body_format: 'json'
      headers:
        Content-Type: "application/json"
        Accept: "application/json"
      validate_certs: no
    register: existing_credentials


  - name: Validate All Created Credentials
    assert:
      that:
        - item.name in existing_credentials.json.results | map(attribute='name') | list

    loop: "{{ansible_tower.credentials}}"
    loop_control:
      label: "{{item.name}}"

  when:
  - ansible_tower.credentials is defined
