---
- name: Automate LDAP Config on Tower
  hosts: localhost
  gather_facts: no
  tasks:
    - include_vars: ldap_data.yml

    - name: Deploy LDAP Config
      import_role:
        name: tower_ldap
      # vars:
