---
- name: Validate Tower Post Deployment
  hosts: localhost
  gather_facts: no
  vars_files:
    - tower_info.yml
  tasks:
    - name: Validate Tower Post Setup
      import_role:
        name: tower-post-validate

