---
# tasks file for tower-add-inventory

- block: # when ansible_tower.inventories is defined

  - name: "Get the existing organizations"
    uri:
      url: "{{ ansible_tower.url | default(default_ansible_tower_url) }}/api/v2/organizations/"
      user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
      password: "{{ ansible_tower.admin_password }}"
      force_basic_auth: yes
      method: GET
      body_format: 'json'
      headers:
        Content-Type: "application/json"
        Accept: "application/json"
      validate_certs: no
    register: existing_organizations_output
  
  - name: "Get the existing projects"
    uri:
      url: "{{ ansible_tower.url | default(default_ansible_tower_url) }}/api/v2/projects/"
      user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
      password: "{{ ansible_tower.admin_password }}"
      force_basic_auth: yes
      method: GET
      body_format: 'json'
      headers:
        Content-Type: "application/json"
        Accept: "application/json"
      validate_certs: no
    register: existing_projects_output

  # - name: "Get the existing credentials"
  #   rest_get:
  #     host_url: "{{ ansible_tower.url | default(default_ansible_tower_url) }}"
  #     rest_user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
  #     rest_password: "{{ ansible_tower.admin_password }}"
  #     api_uri: "/api/v2/credentials/"
  #   register: existing_credentials_output

  - name: "Process the inventory entries"
    include_tasks: add-inventory.yml
    with_items:
    - "{{ ansible_tower.inventories }}"
    loop_control:
      loop_var: inventory


  when:
  - ansible_tower.inventories is defined